Repository jphill19/rancid-tomatillos-starter, pull requests merged in 2024-10, with the labels that each got.

#4 Finished Iteration 1
  src/App/App.css
  src/App/App.js
  src/component/Mcard/mcard.component.css
  src/component/Mcard/mcard.component.jsx
  src/component/McardContainer/mcardcontainer.component.css
  src/component/McardContainer/mcardcontainer.component.jsx
  src/index.css
Labels: iteration_1

#6 Added voting to each one of our card components
  src/assets/ArrowImages/arrow-down.svg
  src/assets/ArrowImages/arrow-up.svg
  src/component/ArrowButton/arrowbutton.component.jsx
  src/component/ArrowButton/arrowbutton.css
  src/component/Mcard/mcard.component.jsx
  src/component/Mcard/mcard.css
  src/component/McardContainer/mcardcontainer.component.jsx
  src/component/McardContainer/mcardcontainer.css
Labels: iteration_2

#11 second bullet point for iteration for complete
  src/component/Mdetails/mdetails.component.jsx
Labels: iteration_4
